name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger on push to main branch (change to your branch if needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no prowebsy@185.119.89.240 "cd /home/prowebsy/radijator.prowebsystems.rs && git pull origin main"
